version: '3.7'
services:
  zoo1:
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION:-latest}
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888
    volumes:
      - "./volumes/zookeeper1/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper1/transactions:/var/lib/zookeeper/log"
    networks:
      - ${GLOBAL_NETWORK:-kafka}
  zoo2:
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION:-latest}
    hostname: zoo2
    container_name: zoo2
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888
    volumes:
      - "./volumes/zookeeper2/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper2/transactions:/var/lib/zookeeper/log"
    networks:
      - ${GLOBAL_NETWORK:-kafka}
  zoo3:
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION:-latest}
    hostname: zoo3
    container_name: zoo3
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888
    volumes:
      - "./volumes/zookeeper3/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper3/transactions:/var/lib/zookeeper/log"
    networks:
      - ${GLOBAL_NETWORK:-kafka}